### ISSUE TITLE
@wltrsjames—are you there?

### ISSUE THREAD

**Issue by Defrilitus** [wltrsjames/Ultrawide-Video#24]
You haven't replied to any comments over the past six months. Are you still there or have you abandoned the extension?

**Comment by wltrsjames** [comment]
Sorry Defrilitus,
I haven't abandoned the extension. I've been very busy.

What would you like to know friend?
-James

**Comment by Defrilitus** [comment]
Glad to know that you're still taking care of this extension. Thanks!
