### ISSUE TITLE
Netflix

### ISSUE THREAD

**Issue by Jeppe-Nielsen** [wltrsjames/Ultrawide-Video#5]
Hi I haven't been able to use the extension on Netflix for awhile - I tried to figure out why so i looked at their code and your code - they have changed the class { selector: ".video-container div video", className: "extraClass" }, // Netflix doesn't work anymore

{ selector: ".player-video-wrapper", className: "NetflixExtraClass" }, // Netflix 
.NetflixExtraClass {
    height: 133.9%!important;
    width: 100%!important;
    left: 0%!important;
    top: 0%!important;
    position:absolute!important;
    transform: translateY(-12.5%)!important;
}

The video displays correctly when I style the class .player-video-wrapper but the subtitles are placed wrong - either too low or too high. 

There are two classes which control the subtitles - player-timedtext and player-timedtext-text-container They both get rewritten with inline styling when the windows size is changed so haven't figured out how to fix that..

**Comment by wltrsjames** [comment]
Thanks for the research friend, I think I've fixed this now. If not please let me know :)
