### ISSUE TITLE
New version doesn't work on macOS.

### ISSUE THREAD

**Issue by f3doraco** [wltrsjames/Ultrawide-Video#8]
Since the new update the plugin doesn't work correctly.

The videos are cropped/stretched in the non-fullscreen mode but in fullscreen they are displayed normally (black bars).

**Comment by wltrsjames** [comment]
Hi there, I have been speaking to another user and it seems like my logic for working out when the browser is in fullscreen mode is wrong. Standby, a hotfix is coming up with the hour

**Comment by f3doraco** [comment]
The Hotfix fixed the bug! Everything is working correctly now.
